-- Your SQL goes here
CREATE TABLE "users" (
  "u_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "u_nickname" varchar(32) NOT NULL DEFAULT 'momo',
  "u_email" varchar(32) UNIQUE NOT NULL,
  "u_password" varchar(32) NOT NULL,
  "u_avatar" varchar(32) NOT NULL,
  "u_is_online" bool NOT NULL DEFAULT false,
  "u_creattime" timestamp NOT NULL,
  "u_lastlogin" timestamp NOT NULL
);

CREATE TABLE "chatroom" (
  "c_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "c_name" varchar(32) NOT NULL DEFAULT '聊天室',
  "c_have_password" bool NOT NULL DEFAULT false,
  "c_password" varchar(32),
  "c_owner" int
);

CREATE TABLE "chatroom_users" (
  "cu_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cu_c_id" int,
  "cu_u_id" int
);

CREATE TABLE "message" (
  "m_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "m_cu_id" int,
  "content" varchar(255) NOT NULL DEFAULT '',
  "creatime" timestamp
);

CREATE INDEX ON "users" ("u_id", "u_nickname");

CREATE INDEX ON "users" ("u_email", "u_password");

CREATE INDEX ON "users" ("u_lastlogin");

CREATE INDEX ON "users" ("u_is_online");

CREATE INDEX ON "users" ("u_nickname", "u_avatar");

CREATE INDEX ON "chatroom" ("c_id", "c_name");

CREATE INDEX ON "chatroom" ("c_have_password", "c_password");

CREATE INDEX ON "chatroom" ("c_owner");

CREATE INDEX ON "chatroom_users" ("cu_c_id", "cu_u_id");

CREATE INDEX ON "chatroom_users" ("cu_id", "cu_u_id");

CREATE INDEX ON "message" ("m_cu_id", "content", "creatime");

ALTER TABLE "chatroom" ADD FOREIGN KEY ("c_owner") REFERENCES "users" ("u_id");

ALTER TABLE "chatroom_users" ADD FOREIGN KEY ("cu_c_id") REFERENCES "chatroom" ("c_id");

ALTER TABLE "chatroom_users" ADD FOREIGN KEY ("cu_u_id") REFERENCES "users" ("u_id");

ALTER TABLE "message" ADD FOREIGN KEY ("m_cu_id") REFERENCES "chatroom_users" ("cu_id");